[package]
name = "rustformers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.14.0"
llm = "0.1.1"
rand = "0.8.5"
serde = "1.0.197"
