volumes:
  models:
    driver: local
    driver_opts:
      type: none
      device: ./models/
      o: bind

services:
  rag-api:
    container_name: rag-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - llm-store
    volumes:
      - models:/app/models
    environment:
      RagApi_Database__Url: "postgres://myuser:mypassword@postgres:5432/mydatabase"
      RagApi_Model__Path: /app/models/open_llama_3b-f16.bin
      RagApi_Api__Address: "0.0.0.0"
      RagApi_Api__Port: "3000"
      RagApi_API__Request_Body_Limit: 1288490188

  postgres:
    container_name: postgres
    hostname: postgres # `server` in adminer
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  llm-store:
    container_name: models
    hostname: models
    image: ksears/llm-store:llama-3b-16f
    volumes:
      - models:/app/models
    user: "1000:1000"

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
