volumes:
  ollama:

services:
  rag-api:
    container_name: rag-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - ollama
    environment:
      RAG_DATABASE_URL: "postgres://myuser:mypassword@postgres:5432/mydatabase"
      RAG_MODEL_ADDRESS: "http://ollama"
      RAG_MODEL_PORT: 11434
      RAG_MODEL_NAME: "llama3.1:latest"
      RAG_API_ADDRESS: "0.0.0.0"
      RAG_API_PORT: "3000"
      RAG_API_REQUEST_BODY_LIMIT: 1288490188

  postgres:
    container_name: postgres
    hostname: postgres # `server` in adminer
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ollama:
    container_name: ollama
    hostname: ollama
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    volumes:
      - ollama:/root/.ollama
    restart: always

  modelchecker:
    container_name: modelchecker
    image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
    entrypoint: ["sh", "-c", "./modelcheck.sh"]
    volumes:
      - ./resources/scripts/modelcheck.sh:/modelcheck.sh
    depends_on:
      - ollama
    environment:
      OLLAMA_API_ENDPOINT: "http://ollama:11434"