name: ci

on:
  workflow_dispatch:
  push:
    branches: 
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
  
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v1
        with:
          access_token: ${{ secrets.BITWARDEN_ACCESS_TOKEN }}
          secrets: |
            5a23fda1-1f10-4ee7-bfc9-b15200eebd70 > DOCKER_USERNAME
            f0c39faf-971c-4cf5-96c8-b15200eee97c > DOCKER_PASSWORD

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ksears/rag-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ksears/rag-api:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
            